Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -5,15 +5,12 @@ orbs:
 commands:
   destroy-environment:
     description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
-    parameters:
-      # Add parameter here   
     steps:
       - run:
           name: Destroy environments
           when: on_fail
           command: |
-            aws cloudformation destroy \
-            --stack-name "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}" \ 
+            aws cloudformation destroy --stack-name "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}"
 
 jobs:
   build-frontend:
@@ -141,7 +138,8 @@ jobs:
               --tags project=udapeople \
               --stack-name "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}" \
               --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"
-              exit 1
+            exit 1
+            
               
       - run:
           name: Ensure front-end infrastructure exist
@@ -150,8 +148,7 @@ jobs:
               --template-file .circleci/files/frontend.yml \
               --tags project=udapeople \
               --stack-name "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}" \
-              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}" 
-            exit 1 
+              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  
       
       - run:
           name: Add back-end ip to ansible inventory
@@ -161,12 +158,17 @@ jobs:
             PUBLIC_IP=$(aws ec2 describe-instances --instance-ids $INSTANCE_ID --query 'Reservations[0].Instances[0].PublicIpAddress' --output text)
 
             echo $PUBLIC_IP >> inventory.txt
-            exit 1
 
       - persist_to_workspace:
           root: ~/
           paths:
             - project/.circleci/ansible/inventory.txt
+      
+      - run:
+         name: run on error
+         command: |
+           echo "hello error!"
+         when: on_fail
       
 workflows:
   default:
