Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -11,6 +11,7 @@ commands:
           when: on_fail
           command: |
             aws cloudformation destroy --stack-name "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}"
+            aws cloudformation destroy --stack-name "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}"
 
 jobs:
   build-frontend:
@@ -148,7 +149,8 @@ jobs:
               --template-file .circleci/files/frontend.yml \
               --tags project=udapeople \
               --stack-name "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}" \
-              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  
+              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"
+            exit 1
       
       - run:
           name: Add back-end ip to ansible inventory
@@ -157,18 +159,22 @@ jobs:
 
             PUBLIC_IP=$(aws ec2 describe-instances --instance-ids $INSTANCE_ID --query 'Reservations[0].Instances[0].PublicIpAddress' --output text)
 
-            echo $PUBLIC_IP >> inventory.txt
+            echo $PUBLIC_IP > inventory.txt
 
+            cat inventory.txt
+            
       - persist_to_workspace:
           root: ~/
           paths:
             - project/.circleci/ansible/inventory.txt
-      
-      - run:
-         name: run on error
-         command: |
-           echo "hello error!"
-         when: on_fail
+
+      - destroy-environment
+
+#      - run:
+#         name: run on error
+#         command: |
+#           
+#         when: on_fail
       
 workflows:
   default:
